name: Create release
on:

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
   release:
     types:
       - created
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip Folder
      run: zip -r Platforms.zip ./Platforms/_images

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Platforms.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
