name: Create release
on: workflow_dispatch
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip Folder
        run: cd home; zip -r Platforms.zip Platforms

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .home/Platforms.zip
        
