name: Create release
on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
   release:
     types:
       - created
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.zip ./Platforms/_images
    - name: "Upload ${{ github.event.repository.name }}.zip Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: "${{ github.event.repository.name }}.zip"
        path: "${{ github.event.repository.name }}/Platforms/_images/"
        if-no-files-found: error
        retention-days: 7

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
