name: Create release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Folder
        run: zip -r Platforms.zip ./Platforms/_images

      - name: Create or update a GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Platforms.zip
          prerelease: ${{ contains(github.ref, '-pre') }}
          generate_release_notes: true

